/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrames;

/**
 *
 * @author murph
 */
public class EventDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventDetailsPanel
     */
    public EventDetailsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EventTitleLabel = new javax.swing.JLabel();
        EventInstructionsLabel = new javax.swing.JLabel();
        EventNameLabel = new javax.swing.JLabel();
        EventNameTF = new javax.swing.JTextField();
        EventDateLabel = new javax.swing.JLabel();
        EventDateTF = new javax.swing.JTextField();
        StartEventBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(869, 501));

        EventTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EventTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        EventTitleLabel.setText("Event Details Page:");

        EventInstructionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EventInstructionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        EventInstructionsLabel.setText("Please enter the details for the current event:");

        EventNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EventNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        EventNameLabel.setText("Event Name:");

        EventNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventNameTFActionPerformed(evt);
            }
        });

        EventDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EventDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        EventDateLabel.setText("Event Date:");

        EventDateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventDateTFActionPerformed(evt);
            }
        });

        StartEventBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StartEventBtn.setText("Start Event");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EventInstructionsLabel)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StartEventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EventNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(EventDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EventDateTF, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(EventNameTF))
                .addGap(181, 181, 181))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(370, Short.MAX_VALUE)
                    .addComponent(EventTitleLabel)
                    .addGap(275, 275, 275)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(EventInstructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventNameLabel)
                    .addComponent(EventNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventDateLabel)
                    .addComponent(EventDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(StartEventBtn)
                .addGap(119, 119, 119))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(EventTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EventNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventNameTFActionPerformed

    private void EventDateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventDateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventDateTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EventDateLabel;
    private javax.swing.JTextField EventDateTF;
    private javax.swing.JLabel EventInstructionsLabel;
    private javax.swing.JLabel EventNameLabel;
    private javax.swing.JTextField EventNameTF;
    private javax.swing.JLabel EventTitleLabel;
    private javax.swing.JButton StartEventBtn;
    // End of variables declaration//GEN-END:variables
}
