/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrames;

/**
 *
 * @author murph
 */
public class ItemListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemListPanel
     */
    public ItemListPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemListLabel = new javax.swing.JLabel();
        RemoveAfterwards = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        RemoveBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        RecordSaleBtn = new javax.swing.JButton();
        ExportBtn = new javax.swing.JButton();
        EventsBtn = new javax.swing.JButton();
        LoginBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ItemListLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ItemListLabel.setForeground(new java.awt.Color(255, 255, 255));
        ItemListLabel.setText("Item List: ");
        ItemListLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        RemoveAfterwards.setForeground(new java.awt.Color(255, 255, 255));
        RemoveAfterwards.setText("We can remove these later, just to make sure we can switch between different forms:");

        AddBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddBtn.setText("Add Item");

        RemoveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveBtn.setText("Remove Item");

        UpdateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateBtn.setText("Update Item");

        RecordSaleBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RecordSaleBtn.setText("Record Sale");

        ExportBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExportBtn.setText("Export Transactions");

        EventsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EventsBtn.setText("Back to Events");

        LoginBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginBtn.setText("Login Page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ExportBtn)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(RecordSaleBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UpdateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RemoveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 412, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(EventsBtn)
                                .addGap(18, 18, 18)
                                .addComponent(LoginBtn))
                            .addComponent(RemoveAfterwards, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecordSaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(RemoveAfterwards)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginBtn)
                    .addComponent(EventsBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton EventsBtn;
    private javax.swing.JButton ExportBtn;
    private javax.swing.JLabel ItemListLabel;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton RecordSaleBtn;
    private javax.swing.JLabel RemoveAfterwards;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JButton UpdateBtn;
    // End of variables declaration//GEN-END:variables
}
