/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrames;

/**
 *
 * @author murph
 */
public class ItemListPanel extends javax.swing.JPanel {
    
    private ItemLogMainFrame mainFrame;
    /**
     * Creates new form ItemListPanel
     */
    public ItemListPanel(ItemLogMainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        
        AddBtn.addActionListener(evt -> mainFrame.navigate("ItemCreation"));
        RecordSaleBtn.addActionListener(evt -> mainFrame.navigate("RecordSale"));
        EventsBtn.addActionListener(evt -> mainFrame.navigate("EventDetails"));
        LoginBtn.addActionListener(evt -> mainFrame.navigate("Login"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemListLabel = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        RemoveBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        RecordSaleBtn = new javax.swing.JButton();
        ExportBtn = new javax.swing.JButton();
        EventsBtn = new javax.swing.JButton();
        LoginBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ItemListLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ItemListLabel.setForeground(new java.awt.Color(255, 255, 255));
        ItemListLabel.setText("Item List: ");
        ItemListLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        AddBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddBtn.setText("Add Item");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        RemoveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveBtn.setText("Remove Item");
        RemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateBtn.setText("Update Item");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        RecordSaleBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RecordSaleBtn.setText("Record Sale");
        RecordSaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordSaleBtnActionPerformed(evt);
            }
        });

        ExportBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExportBtn.setText("Export Transactions");
        ExportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportBtnActionPerformed(evt);
            }
        });

        EventsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EventsBtn.setText("Back to Events");
        EventsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventsBtnActionPerformed(evt);
            }
        });

        LoginBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginBtn.setText("Login Page");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ExportBtn)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(RecordSaleBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UpdateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RemoveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 622, Short.MAX_VALUE)
                        .addComponent(EventsBtn)
                        .addGap(18, 18, 18)
                        .addComponent(LoginBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecordSaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginBtn)
                    .addComponent(EventsBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnActionPerformed

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RemoveBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void RecordSaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordSaleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecordSaleBtnActionPerformed

    private void ExportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ExportBtnActionPerformed

    private void EventsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventsBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton EventsBtn;
    private javax.swing.JButton ExportBtn;
    private javax.swing.JLabel ItemListLabel;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton RecordSaleBtn;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JButton UpdateBtn;
    // End of variables declaration//GEN-END:variables
}
