/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrames;

/**
 *
 * @author murph
 */
public class ItemCreationPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemCreationPanel
     */
    public ItemCreationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemCreationLabel = new javax.swing.JLabel();
        ItemNameLabel = new javax.swing.JLabel();
        ItemNameTF = new javax.swing.JTextField();
        PriceLabel = new javax.swing.JLabel();
        PriceTF = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityTF = new javax.swing.JTextField();
        SizesLabel = new javax.swing.JLabel();
        SizesTF = new javax.swing.JTextField();
        ItemDescriptionLabel = new javax.swing.JLabel();
        OptionalLabel = new javax.swing.JLabel();
        ItemDesTF = new javax.swing.JTextField();
        SaveItemBtn = new javax.swing.JButton();
        DashboardBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ItemCreationLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ItemCreationLabel.setForeground(new java.awt.Color(255, 255, 255));
        ItemCreationLabel.setText("Item Creation: ");

        ItemNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ItemNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ItemNameLabel.setText("Item Name:");

        ItemNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameTFActionPerformed(evt);
            }
        });

        PriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        PriceLabel.setText("Price:");

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuantityLabel.setText("Quantity:");

        SizesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SizesLabel.setForeground(new java.awt.Color(255, 255, 255));
        SizesLabel.setText("Sizes:");

        ItemDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ItemDescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        ItemDescriptionLabel.setText("Item Description:");

        OptionalLabel.setForeground(new java.awt.Color(255, 255, 255));
        OptionalLabel.setText("(optional)");

        SaveItemBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SaveItemBtn.setText("Save Item");

        DashboardBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DashboardBtn.setText("Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItemDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SizesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OptionalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItemCreationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemNameTF)
                    .addComponent(PriceTF)
                    .addComponent(QuantityTF)
                    .addComponent(SizesTF)
                    .addComponent(ItemDesTF)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(ItemCreationLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemNameLabel)
                    .addComponent(ItemNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityLabel)
                    .addComponent(QuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SizesLabel)
                    .addComponent(SizesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemDesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ItemDescriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OptionalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveItemBtn)
                    .addComponent(DashboardBtn))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ItemNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemNameTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DashboardBtn;
    private javax.swing.JLabel ItemCreationLabel;
    private javax.swing.JTextField ItemDesTF;
    private javax.swing.JLabel ItemDescriptionLabel;
    private javax.swing.JLabel ItemNameLabel;
    private javax.swing.JTextField ItemNameTF;
    private javax.swing.JLabel OptionalLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JTextField PriceTF;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityTF;
    private javax.swing.JButton SaveItemBtn;
    private javax.swing.JLabel SizesLabel;
    private javax.swing.JTextField SizesTF;
    // End of variables declaration//GEN-END:variables
}
