/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrames;

/**
 *
 * @author murph
 */
public class RecordSalesPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecordSalesPanel
     */
    public RecordSalesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecordingSalesLabel = new javax.swing.JLabel();
        ItemSelectedLabel = new javax.swing.JLabel();
        ItemSelectedDescriptionTF = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityTF = new javax.swing.JTextField();
        LogSaleBtn = new javax.swing.JButton();
        DashboardBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(869, 501));

        RecordingSalesLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        RecordingSalesLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecordingSalesLabel.setText("Recording a sale: ");

        ItemSelectedLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ItemSelectedLabel.setForeground(new java.awt.Color(255, 255, 255));
        ItemSelectedLabel.setText("Item Selected");

        ItemSelectedDescriptionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSelectedDescriptionTFActionPerformed(evt);
            }
        });

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuantityLabel.setText("Quantity:");

        QuantityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTFActionPerformed(evt);
            }
        });

        LogSaleBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LogSaleBtn.setText("Log Sale");

        DashboardBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DashboardBtn.setText("Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItemSelectedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(QuantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RecordingSalesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemSelectedDescriptionTF)
                    .addComponent(QuantityTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LogSaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(RecordingSalesLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(ItemSelectedDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ItemSelectedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantityLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogSaleBtn)
                    .addComponent(DashboardBtn))
                .addGap(201, 201, 201))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ItemSelectedDescriptionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSelectedDescriptionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemSelectedDescriptionTFActionPerformed

    private void QuantityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DashboardBtn;
    private javax.swing.JTextField ItemSelectedDescriptionTF;
    private javax.swing.JLabel ItemSelectedLabel;
    private javax.swing.JButton LogSaleBtn;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityTF;
    private javax.swing.JLabel RecordingSalesLabel;
    // End of variables declaration//GEN-END:variables
}
