/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrames;

import dao.UserDAO;
import javax.swing.JOptionPane;

/**
 * 
 * @author murph
 */

// handling new user account creation

// Collecting user details, validating input,
// hashes password, and stores user securely in the database using the UserDAO class. 

public class RegisterPanel extends javax.swing.JPanel {
    // reference to the main application frame for navigation 
    private ItemLogMainFrame mainFrame;
    
    //DAO responsible for user-related database operations
    private UserDAO userDAO = new UserDAO();
    
    // creates RegisterPanel and sets up navigation controls
    public RegisterPanel(ItemLogMainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        
        mainFrame.navigate("Login");
        // navigating back to login screen
        BackBtn.addActionListener(evt -> mainFrame.navigate("Login"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrationLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        RegUserNameTF = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        RegEmailTF = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        CreateAccountBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        RegPasswordTF = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 153, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        RegistrationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegistrationLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationLabel.setText("Registration Form: ");

        UserNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserNameLabel.setText("Username:");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email");

        RegEmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegEmailTFActionPerformed(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Password:");

        CreateAccountBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateAccountBtn.setText("Create Account");
        CreateAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        RegPasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegPasswordTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RegistrationLabel)
                                .addGap(0, 48, Short.MAX_VALUE))
                            .addComponent(RegUserNameTF)
                            .addComponent(RegEmailTF)
                            .addComponent(RegPasswordTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreateAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BackBtn)))
                .addGap(298, 298, 298))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(RegistrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegUserNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameLabel))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(RegPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAccountBtn)
                    .addComponent(BackBtn))
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegEmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegEmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegEmailTFActionPerformed
    // V=validates user input 
    // hashes the password
    // stores user details securely via UserDAO
    private void CreateAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountBtnActionPerformed

    // retrieving and sanitising user input 
    String username = RegUserNameTF.getText().trim();
    String email = RegEmailTF.getText().trim();
    String password = RegPasswordTF.getText().trim();
    
    //input validation 
    if (username.isEmpty() || email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "All fields must be filled.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // hashing the password before storing it 
    String hashed = Integer.toHexString(password.hashCode());

    // attempting to create the user in the database
    boolean success = userDAO.createUser(username, email, hashed);

    if (success) {
        JOptionPane.showMessageDialog(this, 
            "Account created successfully!");
        mainFrame.navigate("Login");
    } else {
        JOptionPane.showMessageDialog(this, 
            "Username or email already exists.", "Error", JOptionPane.ERROR_MESSAGE);
    }


        
    }//GEN-LAST:event_CreateAccountBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BackBtnActionPerformed

    private void RegPasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegPasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegPasswordTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CreateAccountBtn;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField RegEmailTF;
    private javax.swing.JPasswordField RegPasswordTF;
    private javax.swing.JTextField RegUserNameTF;
    private javax.swing.JLabel RegistrationLabel;
    private javax.swing.JLabel UserNameLabel;
    // End of variables declaration//GEN-END:variables
}
