package com.itemlog.itemlogapi.dto;

// Response DTO returned after successful login.
// Includes the JWT used by the Android app for protected API requests.
public class LoginResponse {

    // Database ID of the logged-in user.
    private Integer userId;

    // Username of the logged-in user.
    private String username;

    // Email address of the logged-in user.
    private String email;

    // JWT token generated by the backend.
    // The Android app stores this and sends it with protected API requests.
    private String token;


    public LoginResponse() {}

    // Constructor used to create a complete login response.
    public LoginResponse(Integer userId, String username, String email, String token) {
        this.userId = userId;
        this.username = username;
        this.email = email;
        this.token = token;
    }

    public Integer getUserId() { return userId; }
    public void setUserId(Integer userId) { this.userId = userId; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getToken() { return token; }
    public void setToken(String token) { this.token = token; }
}
